import { DEFAULT_MAIN_PRESET_URL } from "@/lib/main-image-presets";
import type { CardData } from "./types";

export const INITIAL_CARD_DATA: CardData = {
  style: { primaryColor: "#882CDF", bgColor: "#FFFFFF", fontFamily: "Pretendard", borderRadius: "8px" },
  music: { selectedId: "march-1", uploadedFile: null, isLoop: true },
  theme: {
    fontFamily: "Pretendard",
    fontScale: "md",
    colorPreset: "spring-blossom",
    bgm: "none",
    bgmAutoplay: false,
    scrollEffect: true,
    particleEffect: "none",
  },
  main: {
    image: "",
    images: [],
    title: "김햇님 ♥ 김별님 결혼식",
    titleColor: "#333333",
    bodyColor: "#666666",
    animation: "없음",
    introType: "A",
    imageMode: "default",
    presetImage: DEFAULT_MAIN_PRESET_URL,
    transitionEffect: "없음",
    transitionIntervalSec: 3,
    imageFrame: "full",
    blackAndWhite: false,
  },
  hosts: {
    groom: {
      name: "김햇님",
      phone: "010-0000-0000",
      relation: "장남",
      father: { name: "", phone: "", isDeceased: false, isOn: true },
      mother: { name: "", phone: "", isDeceased: false, isOn: true },
    },
    bride: {
      name: "김별님",
      phone: "010-1111-1111",
      relation: "장녀",
      father: { name: "", phone: "", isDeceased: false, isOn: true },
      mother: { name: "", phone: "", isDeceased: false, isOn: true },
    },
    showContacts: false,
  },
  eventInfo: {
    date: "2026-11-21",
    time: "오후 2:30",
    venueName: "라움아트센터",
    venueDetail: "5층 라움홀",
    showDday: true,
    calendarDisplayType: "A",
    calendarUseThemeColor: false,
  },
  greeting: {
    title: "초대합니다",
    content: "서로가 마주보며 다져온 사랑을\n이제 함께 한 곳을 바라보며\n걸어가고자 합니다.",
  },
  intro: {
    sectionHeading: "저희를 소개합니다",
    layoutType: "A",
    groom: {
      image: "",
      birthDate: "1995.04.21",
      mbti: "ENFP",
      hobbies: "",
      traits: "웃음이 많고 다정한 사람입니다.",
    },
    bride: {
      image: "",
      birthDate: "1996.07.15",
      mbti: "ISFJ",
      hobbies: "",
      traits: "따뜻한 마음으로 주변을 밝히는 사람입니다.",
    },
  },
  notice: {
    title: "안내사항",
    content: "마음 편히 오셔서 함께 축복해 주세요.\n예식장 내 주차가 가능하며, 식전 30분 전부터 입장이 가능합니다.",
    sectionHeading: "안내사항",
  },
  location: {
    title: "오시는 길",
    address: "",
    car: "",
    bus: "",
    subway: "",
    transports: [],
    mapProvider: "naver",
    mapType: "photo",
  },
  accounts: {
    title: "마음 전하실 곳",
    content: "",
    displayMode: "accordion",
    list: [
      {
        id: "groom-1",
        groupName: "신랑측 계좌",
        bank: "",
        accountNumber: "",
        holder: "",
        isKakaoPay: false,
        isExpanded: true,
      },
      {
        id: "bride-1",
        groupName: "신부측 계좌",
        bank: "",
        accountNumber: "",
        holder: "",
        isKakaoPay: false,
        isExpanded: true,
      },
    ],
  },
  gallery: { isOn: true, type: "swipe", images: [], imageGap: "middle", useLoadMore: true },
  guestbook: {
    isOn: false,
    title: "축하해 주세요",
    description: "축하 인사를 남겨주세요.",
    password: "",
    allowAnonymous: true,
    requireApproval: false,
    entries: [],
  },
  youtube: { isOn: false, title: "영상으로 전하는 마음", url: "", isLoop: false, sourceType: "url", fileUrl: "" },
  guestUpload: {
    isOn: true,
    title: "추억을 공유해 주세요",
    description: "예식 후 촬영하신 사진/영상을 업로드해 주세요.",
    storageGb: 2,
    showAfterEventModal: true,
  },
  share: {
    useThumbnail: true,
    thumbnail: "",
    title: "김햇님 ♥ 김별님 결혼식",
    description: "서로가 마주보며 다져온 사랑을 이제 함께 한 곳을 바라보며 걸어가고자 합니다.",
    link: "",
    enableCopy: true,
    enableKakao: true,
  },
  contact: {
    useThumbnail: true,
    thumbnail: "",
  },
  protect: { preventCapture: false, preventZoom: false, preventDownload: false },
  rsvp: {
    title: "참석 여부",
    description: "참석 여부를 알려주시면 준비에 큰 도움이 됩니다.",
    collectGuestCount: true,
    deadline: "",
  },
  publish: {
    publicStartDate: "",
  },
  i18n: {
    enabled: false,
  },
  billing: {
    isPaid: false,
  },
  sectionEnabled: {},
};
